name: Build Electron App for Windows

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3.5.2

      - name: Setup Node.js
        uses: actions/setup-node@v3.8.1
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Windows Installer
        run: npm run make

      - name: Upload artifact
        uses: actions/upload-artifact@v3.1.2
        with:
          name: windows-build
          path: out/make/**
